/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongSlugRouteImport } from './routes/song.$slug'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiSpotifySearchRouteImport } from './routes/api/spotify/search'
import { Route as ApiSpotifyNewReleasesRouteImport } from './routes/api/spotify/new-releases'
import { Route as ApiSpotifyImportRouteImport } from './routes/api/spotify/import'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSlugRoute = SongSlugRouteImport.update({
  id: '/song/$slug',
  path: '/song/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSpotifySearchRoute = ApiSpotifySearchRouteImport.update({
  id: '/api/spotify/search',
  path: '/api/spotify/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyNewReleasesRoute = ApiSpotifyNewReleasesRouteImport.update({
  id: '/api/spotify/new-releases',
  path: '/api/spotify/new-releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyImportRoute = ApiSpotifyImportRouteImport.update({
  id: '/api/spotify/import',
  path: '/api/spotify/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/song/$slug': typeof SongSlugRoute
  '/api/spotify/import': typeof ApiSpotifyImportRoute
  '/api/spotify/new-releases': typeof ApiSpotifyNewReleasesRoute
  '/api/spotify/search': typeof ApiSpotifySearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/song/$slug': typeof SongSlugRoute
  '/api/spotify/import': typeof ApiSpotifyImportRoute
  '/api/spotify/new-releases': typeof ApiSpotifyNewReleasesRoute
  '/api/spotify/search': typeof ApiSpotifySearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/song/$slug': typeof SongSlugRoute
  '/api/spotify/import': typeof ApiSpotifyImportRoute
  '/api/spotify/new-releases': typeof ApiSpotifyNewReleasesRoute
  '/api/spotify/search': typeof ApiSpotifySearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/song/$slug'
    | '/api/spotify/import'
    | '/api/spotify/new-releases'
    | '/api/spotify/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/song/$slug'
    | '/api/spotify/import'
    | '/api/spotify/new-releases'
    | '/api/spotify/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/song/$slug'
    | '/api/spotify/import'
    | '/api/spotify/new-releases'
    | '/api/spotify/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SongSlugRoute: typeof SongSlugRoute
  ApiSpotifyImportRoute: typeof ApiSpotifyImportRoute
  ApiSpotifyNewReleasesRoute: typeof ApiSpotifyNewReleasesRoute
  ApiSpotifySearchRoute: typeof ApiSpotifySearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$slug': {
      id: '/song/$slug'
      path: '/song/$slug'
      fullPath: '/song/$slug'
      preLoaderRoute: typeof SongSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/spotify/search': {
      id: '/api/spotify/search'
      path: '/api/spotify/search'
      fullPath: '/api/spotify/search'
      preLoaderRoute: typeof ApiSpotifySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/new-releases': {
      id: '/api/spotify/new-releases'
      path: '/api/spotify/new-releases'
      fullPath: '/api/spotify/new-releases'
      preLoaderRoute: typeof ApiSpotifyNewReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/import': {
      id: '/api/spotify/import'
      path: '/api/spotify/import'
      fullPath: '/api/spotify/import'
      preLoaderRoute: typeof ApiSpotifyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SongSlugRoute: SongSlugRoute,
  ApiSpotifyImportRoute: ApiSpotifyImportRoute,
  ApiSpotifyNewReleasesRoute: ApiSpotifyNewReleasesRoute,
  ApiSpotifySearchRoute: ApiSpotifySearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
