/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SongSlugRouteImport } from './routes/song.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiArtistRequestsRouteImport } from './routes/api/artist-requests'
import { Route as AlbumSlugRouteImport } from './routes/album.$slug'
import { Route as AdminLogRouteImport } from './routes/admin/log'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AdminSongsIndexRouteImport } from './routes/admin/songs/index'
import { Route as AdminArtistsIndexRouteImport } from './routes/admin/artists/index'
import { Route as AdminAlbumsIndexRouteImport } from './routes/admin/albums/index'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as ApiAdminUploadArtworkRouteImport } from './routes/api/admin/upload-artwork'
import { Route as ApiAdminUpdateSongArtistsRouteImport } from './routes/api/admin/update-song-artists'
import { Route as ApiAdminUpdateSongRouteImport } from './routes/api/admin/update-song'
import { Route as ApiAdminUpdateReleaseGroupRouteImport } from './routes/api/admin/update-release-group'
import { Route as ApiAdminUpdateArtistRouteImport } from './routes/api/admin/update-artist'
import { Route as ApiAdminSearchEntitiesRouteImport } from './routes/api/admin/search-entities'
import { Route as AdminSongsSlugRouteImport } from './routes/admin/songs/$slug'
import { Route as AdminArtistsSlugRouteImport } from './routes/admin/artists/$slug'
import { Route as AdminAlbumsSlugRouteImport } from './routes/admin/albums/$slug'
import { Route as AuthenticatedUserUsernameRouteImport } from './routes/_authenticated/user.$username'
import { Route as AuthenticatedConnectUsernameRouteImport } from './routes/_authenticated/connect.$username'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SongSlugRoute = SongSlugRouteImport.update({
  id: '/song/$slug',
  path: '/song/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtistRequestsRoute = ApiArtistRequestsRouteImport.update({
  id: '/api/artist-requests',
  path: '/api/artist-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumSlugRoute = AlbumSlugRouteImport.update({
  id: '/album/$slug',
  path: '/album/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminSongsIndexRoute = AdminSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistsIndexRoute = AdminArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlbumsIndexRoute = AdminAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadArtworkRoute = ApiAdminUploadArtworkRouteImport.update({
  id: '/api/admin/upload-artwork',
  path: '/api/admin/upload-artwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateSongArtistsRoute =
  ApiAdminUpdateSongArtistsRouteImport.update({
    id: '/api/admin/update-song-artists',
    path: '/api/admin/update-song-artists',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUpdateSongRoute = ApiAdminUpdateSongRouteImport.update({
  id: '/api/admin/update-song',
  path: '/api/admin/update-song',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateReleaseGroupRoute =
  ApiAdminUpdateReleaseGroupRouteImport.update({
    id: '/api/admin/update-release-group',
    path: '/api/admin/update-release-group',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUpdateArtistRoute = ApiAdminUpdateArtistRouteImport.update({
  id: '/api/admin/update-artist',
  path: '/api/admin/update-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSearchEntitiesRoute = ApiAdminSearchEntitiesRouteImport.update({
  id: '/api/admin/search-entities',
  path: '/api/admin/search-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSongsSlugRoute = AdminSongsSlugRouteImport.update({
  id: '/songs/$slug',
  path: '/songs/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistsSlugRoute = AdminArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlbumsSlugRoute = AdminAlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedUserUsernameRoute =
  AuthenticatedUserUsernameRouteImport.update({
    id: '/user/$username',
    path: '/user/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectUsernameRoute =
  AuthenticatedConnectUsernameRouteImport.update({
    id: '/connect/$username',
    path: '/connect/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/log': typeof AdminLogRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/api/artist-requests': typeof ApiArtistRequestsRoute
  '/api/import': typeof ApiImportRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/song/$slug': typeof SongSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/connect/$username': typeof AuthenticatedConnectUsernameRoute
  '/user/$username': typeof AuthenticatedUserUsernameRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/admin/songs/$slug': typeof AdminSongsSlugRoute
  '/api/admin/search-entities': typeof ApiAdminSearchEntitiesRoute
  '/api/admin/update-artist': typeof ApiAdminUpdateArtistRoute
  '/api/admin/update-release-group': typeof ApiAdminUpdateReleaseGroupRoute
  '/api/admin/update-song': typeof ApiAdminUpdateSongRoute
  '/api/admin/update-song-artists': typeof ApiAdminUpdateSongArtistsRoute
  '/api/admin/upload-artwork': typeof ApiAdminUploadArtworkRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/admin/artists/': typeof AdminArtistsIndexRoute
  '/admin/songs/': typeof AdminSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/log': typeof AdminLogRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/api/artist-requests': typeof ApiArtistRequestsRoute
  '/api/import': typeof ApiImportRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/song/$slug': typeof SongSlugRoute
  '/admin': typeof AdminIndexRoute
  '/connect/$username': typeof AuthenticatedConnectUsernameRoute
  '/user/$username': typeof AuthenticatedUserUsernameRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/admin/songs/$slug': typeof AdminSongsSlugRoute
  '/api/admin/search-entities': typeof ApiAdminSearchEntitiesRoute
  '/api/admin/update-artist': typeof ApiAdminUpdateArtistRoute
  '/api/admin/update-release-group': typeof ApiAdminUpdateReleaseGroupRoute
  '/api/admin/update-song': typeof ApiAdminUpdateSongRoute
  '/api/admin/update-song-artists': typeof ApiAdminUpdateSongArtistsRoute
  '/api/admin/upload-artwork': typeof ApiAdminUploadArtworkRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/admin/albums': typeof AdminAlbumsIndexRoute
  '/admin/artists': typeof AdminArtistsIndexRoute
  '/admin/songs': typeof AdminSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/admin/log': typeof AdminLogRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/api/artist-requests': typeof ApiArtistRequestsRoute
  '/api/import': typeof ApiImportRoute
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/song/$slug': typeof SongSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/connect/$username': typeof AuthenticatedConnectUsernameRoute
  '/_authenticated/user/$username': typeof AuthenticatedUserUsernameRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/admin/songs/$slug': typeof AdminSongsSlugRoute
  '/api/admin/search-entities': typeof ApiAdminSearchEntitiesRoute
  '/api/admin/update-artist': typeof ApiAdminUpdateArtistRoute
  '/api/admin/update-release-group': typeof ApiAdminUpdateReleaseGroupRoute
  '/api/admin/update-song': typeof ApiAdminUpdateSongRoute
  '/api/admin/update-song-artists': typeof ApiAdminUpdateSongArtistsRoute
  '/api/admin/upload-artwork': typeof ApiAdminUploadArtworkRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/admin/artists/': typeof AdminArtistsIndexRoute
  '/admin/songs/': typeof AdminSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/onboarding'
    | '/home'
    | '/admin/log'
    | '/album/$slug'
    | '/api/artist-requests'
    | '/api/import'
    | '/api/search'
    | '/api/upload'
    | '/artist/$slug'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/song/$slug'
    | '/admin/'
    | '/connect/$username'
    | '/user/$username'
    | '/admin/albums/$slug'
    | '/admin/artists/$slug'
    | '/admin/songs/$slug'
    | '/api/admin/search-entities'
    | '/api/admin/update-artist'
    | '/api/admin/update-release-group'
    | '/api/admin/update-song'
    | '/api/admin/update-song-artists'
    | '/api/admin/upload-artwork'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/admin/albums/'
    | '/admin/artists/'
    | '/admin/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/home'
    | '/admin/log'
    | '/album/$slug'
    | '/api/artist-requests'
    | '/api/import'
    | '/api/search'
    | '/api/upload'
    | '/artist/$slug'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/song/$slug'
    | '/admin'
    | '/connect/$username'
    | '/user/$username'
    | '/admin/albums/$slug'
    | '/admin/artists/$slug'
    | '/admin/songs/$slug'
    | '/api/admin/search-entities'
    | '/api/admin/update-artist'
    | '/api/admin/update-release-group'
    | '/api/admin/update-song'
    | '/api/admin/update-song-artists'
    | '/api/admin/upload-artwork'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/admin/albums'
    | '/admin/artists'
    | '/admin/songs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/onboarding'
    | '/_authenticated/home'
    | '/admin/log'
    | '/album/$slug'
    | '/api/artist-requests'
    | '/api/import'
    | '/api/search'
    | '/api/upload'
    | '/artist/$slug'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/song/$slug'
    | '/admin/'
    | '/_authenticated/connect/$username'
    | '/_authenticated/user/$username'
    | '/admin/albums/$slug'
    | '/admin/artists/$slug'
    | '/admin/songs/$slug'
    | '/api/admin/search-entities'
    | '/api/admin/update-artist'
    | '/api/admin/update-release-group'
    | '/api/admin/update-song'
    | '/api/admin/update-song-artists'
    | '/api/admin/upload-artwork'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/admin/albums/'
    | '/admin/artists/'
    | '/admin/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AlbumSlugRoute: typeof AlbumSlugRoute
  ApiArtistRequestsRoute: typeof ApiArtistRequestsRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  SongSlugRoute: typeof SongSlugRoute
  ApiAdminSearchEntitiesRoute: typeof ApiAdminSearchEntitiesRoute
  ApiAdminUpdateArtistRoute: typeof ApiAdminUpdateArtistRoute
  ApiAdminUpdateReleaseGroupRoute: typeof ApiAdminUpdateReleaseGroupRoute
  ApiAdminUpdateSongRoute: typeof ApiAdminUpdateSongRoute
  ApiAdminUpdateSongArtistsRoute: typeof ApiAdminUpdateSongArtistsRoute
  ApiAdminUploadArtworkRoute: typeof ApiAdminUploadArtworkRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/song/$slug': {
      id: '/song/$slug'
      path: '/song/$slug'
      fullPath: '/song/$slug'
      preLoaderRoute: typeof SongSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artist-requests': {
      id: '/api/artist-requests'
      path: '/api/artist-requests'
      fullPath: '/api/artist-requests'
      preLoaderRoute: typeof ApiArtistRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$slug': {
      id: '/album/$slug'
      path: '/album/$slug'
      fullPath: '/album/$slug'
      preLoaderRoute: typeof AlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/songs/': {
      id: '/admin/songs/'
      path: '/songs'
      fullPath: '/admin/songs/'
      preLoaderRoute: typeof AdminSongsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artists/': {
      id: '/admin/artists/'
      path: '/artists'
      fullPath: '/admin/artists/'
      preLoaderRoute: typeof AdminArtistsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/albums/': {
      id: '/admin/albums/'
      path: '/albums'
      fullPath: '/admin/albums/'
      preLoaderRoute: typeof AdminAlbumsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-artwork': {
      id: '/api/admin/upload-artwork'
      path: '/api/admin/upload-artwork'
      fullPath: '/api/admin/upload-artwork'
      preLoaderRoute: typeof ApiAdminUploadArtworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-song-artists': {
      id: '/api/admin/update-song-artists'
      path: '/api/admin/update-song-artists'
      fullPath: '/api/admin/update-song-artists'
      preLoaderRoute: typeof ApiAdminUpdateSongArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-song': {
      id: '/api/admin/update-song'
      path: '/api/admin/update-song'
      fullPath: '/api/admin/update-song'
      preLoaderRoute: typeof ApiAdminUpdateSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-release-group': {
      id: '/api/admin/update-release-group'
      path: '/api/admin/update-release-group'
      fullPath: '/api/admin/update-release-group'
      preLoaderRoute: typeof ApiAdminUpdateReleaseGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-artist': {
      id: '/api/admin/update-artist'
      path: '/api/admin/update-artist'
      fullPath: '/api/admin/update-artist'
      preLoaderRoute: typeof ApiAdminUpdateArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/search-entities': {
      id: '/api/admin/search-entities'
      path: '/api/admin/search-entities'
      fullPath: '/api/admin/search-entities'
      preLoaderRoute: typeof ApiAdminSearchEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/songs/$slug': {
      id: '/admin/songs/$slug'
      path: '/songs/$slug'
      fullPath: '/admin/songs/$slug'
      preLoaderRoute: typeof AdminSongsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artists/$slug': {
      id: '/admin/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/admin/artists/$slug'
      preLoaderRoute: typeof AdminArtistsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/albums/$slug': {
      id: '/admin/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/admin/albums/$slug'
      preLoaderRoute: typeof AdminAlbumsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/user/$username': {
      id: '/_authenticated/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AuthenticatedUserUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect/$username': {
      id: '/_authenticated/connect/$username'
      path: '/connect/$username'
      fullPath: '/connect/$username'
      preLoaderRoute: typeof AuthenticatedConnectUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedConnectUsernameRoute: typeof AuthenticatedConnectUsernameRoute
  AuthenticatedUserUsernameRoute: typeof AuthenticatedUserUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedConnectUsernameRoute: AuthenticatedConnectUsernameRoute,
  AuthenticatedUserUsernameRoute: AuthenticatedUserUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminLogRoute: typeof AdminLogRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlbumsSlugRoute: typeof AdminAlbumsSlugRoute
  AdminArtistsSlugRoute: typeof AdminArtistsSlugRoute
  AdminSongsSlugRoute: typeof AdminSongsSlugRoute
  AdminAlbumsIndexRoute: typeof AdminAlbumsIndexRoute
  AdminArtistsIndexRoute: typeof AdminArtistsIndexRoute
  AdminSongsIndexRoute: typeof AdminSongsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLogRoute: AdminLogRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlbumsSlugRoute: AdminAlbumsSlugRoute,
  AdminArtistsSlugRoute: AdminArtistsSlugRoute,
  AdminSongsSlugRoute: AdminSongsSlugRoute,
  AdminAlbumsIndexRoute: AdminAlbumsIndexRoute,
  AdminArtistsIndexRoute: AdminArtistsIndexRoute,
  AdminSongsIndexRoute: AdminSongsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AlbumSlugRoute: AlbumSlugRoute,
  ApiArtistRequestsRoute: ApiArtistRequestsRoute,
  ApiImportRoute: ApiImportRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  SongSlugRoute: SongSlugRoute,
  ApiAdminSearchEntitiesRoute: ApiAdminSearchEntitiesRoute,
  ApiAdminUpdateArtistRoute: ApiAdminUpdateArtistRoute,
  ApiAdminUpdateReleaseGroupRoute: ApiAdminUpdateReleaseGroupRoute,
  ApiAdminUpdateSongRoute: ApiAdminUpdateSongRoute,
  ApiAdminUpdateSongArtistsRoute: ApiAdminUpdateSongArtistsRoute,
  ApiAdminUploadArtworkRoute: ApiAdminUploadArtworkRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
