-- Profile: banner, pronouns, location reference
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS banner_url TEXT,
  ADD COLUMN IF NOT EXISTS pronouns TEXT,
  ADD COLUMN IF NOT EXISTS location_id UUID;

-- Locations table: country + city pairs
CREATE TABLE IF NOT EXISTS public.locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country TEXT NOT NULL,
  city TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (country, COALESCE(city, ''))
);

CREATE INDEX IF NOT EXISTS idx_locations_country ON public.locations (country);
CREATE INDEX IF NOT EXISTS idx_locations_country_city ON public.locations (country, city);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "locations readable by all" ON public.locations FOR SELECT USING (true);
GRANT SELECT ON public.locations TO anon, authenticated;

-- Seed 249 countries with major cities
INSERT INTO public.locations (country, city) VALUES
  ('United States', NULL),
  ('United States', 'New York'),
  ('United States', 'Los Angeles'),
  ('United States', 'Chicago'),
  ('United States', 'Houston'),
  ('United States', 'Phoenix'),
  ('United States', 'Philadelphia'),
  ('United States', 'San Antonio'),
  ('United States', 'San Diego'),
  ('United States', 'Dallas'),
  ('United States', 'Austin'),
  ('United States', 'San Jose'),
  ('United States', 'San Francisco'),
  ('United States', 'Seattle'),
  ('United States', 'Denver'),
  ('United States', 'Nashville'),
  ('United States', 'Portland'),
  ('United States', 'Miami'),
  ('United States', 'Atlanta'),
  ('United States', 'Boston'),
  ('United States', 'Detroit'),
  ('United States', 'Minneapolis'),
  ('United States', 'New Orleans'),
  ('United States', 'Las Vegas'),
  ('United States', 'Washington'),
  ('Canada', NULL),
  ('Canada', 'Toronto'),
  ('Canada', 'Vancouver'),
  ('Canada', 'Montreal'),
  ('Canada', 'Calgary'),
  ('Canada', 'Ottawa'),
  ('Canada', 'Edmonton'),
  ('Canada', 'Winnipeg'),
  ('Canada', 'Quebec City'),
  ('United Kingdom', NULL),
  ('United Kingdom', 'London'),
  ('United Kingdom', 'Manchester'),
  ('United Kingdom', 'Birmingham'),
  ('United Kingdom', 'Glasgow'),
  ('United Kingdom', 'Edinburgh'),
  ('United Kingdom', 'Liverpool'),
  ('United Kingdom', 'Bristol'),
  ('United Kingdom', 'Leeds'),
  ('United Kingdom', 'Cardiff'),
  ('United Kingdom', 'Belfast'),
  ('Germany', NULL),
  ('Germany', 'Berlin'),
  ('Germany', 'Hamburg'),
  ('Germany', 'Munich'),
  ('Germany', 'Cologne'),
  ('Germany', 'Frankfurt'),
  ('Germany', 'Stuttgart'),
  ('Germany', 'Dusseldorf'),
  ('Germany', 'Leipzig'),
  ('Germany', 'Dortmund'),
  ('France', NULL),
  ('France', 'Paris'),
  ('France', 'Marseille'),
  ('France', 'Lyon'),
  ('France', 'Toulouse'),
  ('France', 'Nice'),
  ('France', 'Nantes'),
  ('France', 'Strasbourg'),
  ('France', 'Bordeaux'),
  ('France', 'Lille'),
  ('Italy', NULL),
  ('Italy', 'Rome'),
  ('Italy', 'Milan'),
  ('Italy', 'Naples'),
  ('Italy', 'Turin'),
  ('Italy', 'Florence'),
  ('Italy', 'Bologna'),
  ('Italy', 'Venice'),
  ('Italy', 'Genoa'),
  ('Italy', 'Palermo'),
  ('Spain', NULL),
  ('Spain', 'Madrid'),
  ('Spain', 'Barcelona'),
  ('Spain', 'Valencia'),
  ('Spain', 'Seville'),
  ('Spain', 'Bilbao'),
  ('Spain', 'Malaga'),
  ('Spain', 'Zaragoza'),
  ('Spain', 'Murcia'),
  ('Spain', 'Palma'),
  ('Japan', NULL),
  ('Japan', 'Tokyo'),
  ('Japan', 'Osaka'),
  ('Japan', 'Kyoto'),
  ('Japan', 'Yokohama'),
  ('Japan', 'Nagoya'),
  ('Japan', 'Sapporo'),
  ('Japan', 'Fukuoka'),
  ('Japan', 'Kobe'),
  ('Japan', 'Sendai'),
  ('Australia', NULL),
  ('Australia', 'Sydney'),
  ('Australia', 'Melbourne'),
  ('Australia', 'Brisbane'),
  ('Australia', 'Perth'),
  ('Australia', 'Adelaide'),
  ('Australia', 'Gold Coast'),
  ('Australia', 'Canberra'),
  ('Australia', 'Hobart'),
  ('Australia', 'Darwin'),
  ('Brazil', NULL),
  ('Brazil', 'São Paulo'),
  ('Brazil', 'Rio de Janeiro'),
  ('Brazil', 'Brasília'),
  ('Brazil', 'Salvador'),
  ('Brazil', 'Fortaleza'),
  ('Brazil', 'Belo Horizonte'),
  ('Brazil', 'Curitiba'),
  ('Brazil', 'Recife'),
  ('Brazil', 'Porto Alegre'),
  ('India', NULL),
  ('India', 'Mumbai'),
  ('India', 'Delhi'),
  ('India', 'Bangalore'),
  ('India', 'Hyderabad'),
  ('India', 'Chennai'),
  ('India', 'Kolkata'),
  ('India', 'Pune'),
  ('India', 'Ahmedabad'),
  ('India', 'Jaipur'),
  ('Mexico', NULL),
  ('Mexico', 'Mexico City'),
  ('Mexico', 'Guadalajara'),
  ('Mexico', 'Monterrey'),
  ('Mexico', 'Puebla'),
  ('Mexico', 'Tijuana'),
  ('Netherlands', NULL),
  ('Netherlands', 'Amsterdam'),
  ('Netherlands', 'Rotterdam'),
  ('Netherlands', 'The Hague'),
  ('Netherlands', 'Utrecht'),
  ('Netherlands', 'Eindhoven'),
  ('Sweden', NULL),
  ('Sweden', 'Stockholm'),
  ('Sweden', 'Gothenburg'),
  ('Sweden', 'Malmo'),
  ('Sweden', 'Uppsala'),
  ('Sweden', 'Linkoping'),
  ('Norway', NULL),
  ('Norway', 'Oslo'),
  ('Norway', 'Bergen'),
  ('Norway', 'Trondheim'),
  ('Norway', 'Stavanger'),
  ('Norway', 'Tromso'),
  ('Denmark', NULL),
  ('Denmark', 'Copenhagen'),
  ('Denmark', 'Aarhus'),
  ('Denmark', 'Odense'),
  ('Denmark', 'Aalborg'),
  ('Finland', NULL),
  ('Finland', 'Helsinki'),
  ('Finland', 'Tampere'),
  ('Finland', 'Turku'),
  ('Finland', 'Oulu'),
  ('Iceland', NULL),
  ('Iceland', 'Reykjavik'),
  ('Ireland', NULL),
  ('Ireland', 'Dublin'),
  ('Ireland', 'Cork'),
  ('Ireland', 'Galway'),
  ('Ireland', 'Limerick'),
  ('Belgium', NULL),
  ('Belgium', 'Brussels'),
  ('Belgium', 'Antwerp'),
  ('Belgium', 'Ghent'),
  ('Belgium', 'Bruges'),
  ('Belgium', 'Liege'),
  ('Switzerland', NULL),
  ('Switzerland', 'Zurich'),
  ('Switzerland', 'Geneva'),
  ('Switzerland', 'Basel'),
  ('Switzerland', 'Bern'),
  ('Switzerland', 'Lausanne'),
  ('Austria', NULL),
  ('Austria', 'Vienna'),
  ('Austria', 'Graz'),
  ('Austria', 'Linz'),
  ('Austria', 'Salzburg'),
  ('Austria', 'Innsbruck'),
  ('Portugal', NULL),
  ('Portugal', 'Lisbon'),
  ('Portugal', 'Porto'),
  ('Portugal', 'Braga'),
  ('Portugal', 'Coimbra'),
  ('Portugal', 'Faro'),
  ('Greece', NULL),
  ('Greece', 'Athens'),
  ('Greece', 'Thessaloniki'),
  ('Greece', 'Patras'),
  ('Greece', 'Heraklion'),
  ('Poland', NULL),
  ('Poland', 'Warsaw'),
  ('Poland', 'Krakow'),
  ('Poland', 'Wroclaw'),
  ('Poland', 'Poznan'),
  ('Poland', 'Gdansk'),
  ('Czech Republic', NULL),
  ('Czech Republic', 'Prague'),
  ('Czech Republic', 'Brno'),
  ('Czech Republic', 'Ostrava'),
  ('Czech Republic', 'Plzen'),
  ('Romania', NULL),
  ('Romania', 'Bucharest'),
  ('Romania', 'Cluj-Napoca'),
  ('Romania', 'Timisoara'),
  ('Romania', 'Iasi'),
  ('Hungary', NULL),
  ('Hungary', 'Budapest'),
  ('Hungary', 'Debrecen'),
  ('Hungary', 'Szeged'),
  ('Hungary', 'Miskolc'),
  ('Russia', NULL),
  ('Russia', 'Moscow'),
  ('Russia', 'Saint Petersburg'),
  ('Russia', 'Novosibirsk'),
  ('Russia', 'Yekaterinburg'),
  ('Russia', 'Kazan'),
  ('Turkey', NULL),
  ('Turkey', 'Istanbul'),
  ('Turkey', 'Ankara'),
  ('Turkey', 'Izmir'),
  ('Turkey', 'Bursa'),
  ('Turkey', 'Antalya'),
  ('South Korea', NULL),
  ('South Korea', 'Seoul'),
  ('South Korea', 'Busan'),
  ('South Korea', 'Incheon'),
  ('South Korea', 'Daegu'),
  ('South Korea', 'Daejeon'),
  ('China', NULL),
  ('China', 'Beijing'),
  ('China', 'Shanghai'),
  ('China', 'Guangzhou'),
  ('China', 'Shenzhen'),
  ('China', 'Chengdu'),
  ('Taiwan', NULL),
  ('Taiwan', 'Taipei'),
  ('Taiwan', 'Kaohsiung'),
  ('Taiwan', 'Taichung'),
  ('Taiwan', 'Tainan'),
  ('Singapore', NULL),
  ('Malaysia', NULL),
  ('Malaysia', 'Kuala Lumpur'),
  ('Malaysia', 'Penang'),
  ('Malaysia', 'Johor Bahru'),
  ('Malaysia', 'Kota Kinabalu'),
  ('Indonesia', NULL),
  ('Indonesia', 'Jakarta'),
  ('Indonesia', 'Surabaya'),
  ('Indonesia', 'Bandung'),
  ('Indonesia', 'Medan'),
  ('Indonesia', 'Bali'),
  ('Thailand', NULL),
  ('Thailand', 'Bangkok'),
  ('Thailand', 'Chiang Mai'),
  ('Thailand', 'Phuket'),
  ('Thailand', 'Pattaya'),
  ('Vietnam', NULL),
  ('Vietnam', 'Ho Chi Minh City'),
  ('Vietnam', 'Hanoi'),
  ('Vietnam', 'Da Nang'),
  ('Vietnam', 'Hai Phong'),
  ('Philippines', NULL),
  ('Philippines', 'Manila'),
  ('Philippines', 'Quezon City'),
  ('Philippines', 'Cebu'),
  ('Philippines', 'Davao'),
  ('New Zealand', NULL),
  ('New Zealand', 'Auckland'),
  ('New Zealand', 'Wellington'),
  ('New Zealand', 'Christchurch'),
  ('New Zealand', 'Hamilton'),
  ('New Zealand', 'Dunedin'),
  ('Argentina', NULL),
  ('Argentina', 'Buenos Aires'),
  ('Argentina', 'Cordoba'),
  ('Argentina', 'Rosario'),
  ('Argentina', 'Mendoza'),
  ('Argentina', 'La Plata'),
  ('Chile', NULL),
  ('Chile', 'Santiago'),
  ('Chile', 'Valparaiso'),
  ('Chile', 'Concepcion'),
  ('Chile', 'La Serena'),
  ('Colombia', NULL),
  ('Colombia', 'Bogota'),
  ('Colombia', 'Medellin'),
  ('Colombia', 'Cali'),
  ('Colombia', 'Barranquilla'),
  ('Colombia', 'Cartagena'),
  ('Peru', NULL),
  ('Peru', 'Lima'),
  ('Peru', 'Arequipa'),
  ('Peru', 'Cusco'),
  ('Peru', 'Trujillo'),
  ('South Africa', NULL),
  ('South Africa', 'Johannesburg'),
  ('South Africa', 'Cape Town'),
  ('South Africa', 'Durban'),
  ('South Africa', 'Pretoria'),
  ('South Africa', 'Port Elizabeth'),
  ('Nigeria', NULL),
  ('Nigeria', 'Lagos'),
  ('Nigeria', 'Abuja'),
  ('Nigeria', 'Kano'),
  ('Nigeria', 'Ibadan'),
  ('Nigeria', 'Port Harcourt'),
  ('Kenya', NULL),
  ('Kenya', 'Nairobi'),
  ('Kenya', 'Mombasa'),
  ('Kenya', 'Kisumu'),
  ('Kenya', 'Nakuru'),
  ('Egypt', NULL),
  ('Egypt', 'Cairo'),
  ('Egypt', 'Alexandria'),
  ('Egypt', 'Giza'),
  ('Egypt', 'Luxor'),
  ('Egypt', 'Aswan'),
  ('Morocco', NULL),
  ('Morocco', 'Casablanca'),
  ('Morocco', 'Marrakech'),
  ('Morocco', 'Rabat'),
  ('Morocco', 'Fes'),
  ('Morocco', 'Tangier'),
  ('United Arab Emirates', NULL),
  ('United Arab Emirates', 'Dubai'),
  ('United Arab Emirates', 'Abu Dhabi'),
  ('United Arab Emirates', 'Sharjah'),
  ('United Arab Emirates', 'Al Ain'),
  ('Saudi Arabia', NULL),
  ('Saudi Arabia', 'Riyadh'),
  ('Saudi Arabia', 'Jeddah'),
  ('Saudi Arabia', 'Mecca'),
  ('Saudi Arabia', 'Medina'),
  ('Saudi Arabia', 'Dammam'),
  ('Israel', NULL),
  ('Israel', 'Tel Aviv'),
  ('Israel', 'Jerusalem'),
  ('Israel', 'Haifa'),
  ('Israel', 'Netanya'),
  ('Ukraine', NULL),
  ('Ukraine', 'Kyiv'),
  ('Ukraine', 'Kharkiv'),
  ('Ukraine', 'Odesa'),
  ('Ukraine', 'Lviv'),
  ('Ukraine', 'Dnipro'),
  ('Croatia', NULL),
  ('Croatia', 'Zagreb'),
  ('Croatia', 'Split'),
  ('Croatia', 'Rijeka'),
  ('Croatia', 'Dubrovnik'),
  ('Serbia', NULL),
  ('Serbia', 'Belgrade'),
  ('Serbia', 'Novi Sad'),
  ('Serbia', 'Nis'),
  ('Serbia', 'Kragujevac'),
  ('Bulgaria', NULL),
  ('Bulgaria', 'Sofia'),
  ('Bulgaria', 'Plovdiv'),
  ('Bulgaria', 'Varna'),
  ('Bulgaria', 'Burgas'),
  ('Slovakia', NULL),
  ('Slovakia', 'Bratislava'),
  ('Slovakia', 'Kosice'),
  ('Slovakia', 'Presov'),
  ('Slovakia', 'Zilina'),
  ('Slovenia', NULL),
  ('Slovenia', 'Ljubljana'),
  ('Slovenia', 'Maribor'),
  ('Slovenia', 'Celje'),
  ('Slovenia', 'Koper'),
  ('Estonia', NULL),
  ('Estonia', 'Tallinn'),
  ('Estonia', 'Tartu'),
  ('Estonia', 'Narva'),
  ('Estonia', 'Parnu'),
  ('Latvia', NULL),
  ('Latvia', 'Riga'),
  ('Latvia', 'Daugavpils'),
  ('Latvia', 'Liepaja'),
  ('Latvia', 'Jurmala'),
  ('Lithuania', NULL),
  ('Lithuania', 'Vilnius'),
  ('Lithuania', 'Kaunas'),
  ('Lithuania', 'Klaipeda'),
  ('Lithuania', 'Siauliai'),
  ('Luxembourg', NULL),
  ('Monaco', NULL),
  ('Liechtenstein', NULL),
  ('Malta', NULL),
  ('Cyprus', NULL),
  ('Cyprus', 'Nicosia'),
  ('Cyprus', 'Limassol'),
  ('Cyprus', 'Larnaca'),
  ('Cyprus', 'Paphos'),
  ('Iraq', NULL),
  ('Iraq', 'Baghdad'),
  ('Iraq', 'Basra'),
  ('Iraq', 'Mosul'),
  ('Iraq', 'Erbil'),
  ('Iran', NULL),
  ('Iran', 'Tehran'),
  ('Iran', 'Mashhad'),
  ('Iran', 'Isfahan'),
  ('Iran', 'Shiraz'),
  ('Iran', 'Tabriz'),
  ('Pakistan', NULL),
  ('Pakistan', 'Karachi'),
  ('Pakistan', 'Lahore'),
  ('Pakistan', 'Islamabad'),
  ('Pakistan', 'Rawalpindi'),
  ('Pakistan', 'Faisalabad'),
  ('Bangladesh', NULL),
  ('Bangladesh', 'Dhaka'),
  ('Bangladesh', 'Chittagong'),
  ('Bangladesh', 'Khulna'),
  ('Bangladesh', 'Rajshahi'),
  ('Sri Lanka', NULL),
  ('Sri Lanka', 'Colombo'),
  ('Sri Lanka', 'Kandy'),
  ('Sri Lanka', 'Galle'),
  ('Sri Lanka', 'Jaffna'),
  ('Myanmar', NULL),
  ('Myanmar', 'Yangon'),
  ('Myanmar', 'Mandalay'),
  ('Myanmar', 'Naypyidaw'),
  ('Cambodia', NULL),
  ('Cambodia', 'Phnom Penh'),
  ('Cambodia', 'Siem Reap'),
  ('Cambodia', 'Battambang'),
  ('Laos', NULL),
  ('Laos', 'Vientiane'),
  ('Laos', 'Luang Prabang'),
  ('Nepal', NULL),
  ('Nepal', 'Kathmandu'),
  ('Nepal', 'Pokhara'),
  ('Nepal', 'Lalitpur'),
  ('Bhutan', NULL),
  ('Bhutan', 'Thimphu'),
  ('Mongolia', NULL),
  ('Mongolia', 'Ulaanbaatar'),
  ('Kazakhstan', NULL),
  ('Kazakhstan', 'Almaty'),
  ('Kazakhstan', 'Astana'),
  ('Kazakhstan', 'Shymkent'),
  ('Uzbekistan', NULL),
  ('Uzbekistan', 'Tashkent'),
  ('Uzbekistan', 'Samarkand'),
  ('Uzbekistan', 'Bukhara'),
  ('Georgia', NULL),
  ('Georgia', 'Tbilisi'),
  ('Georgia', 'Batumi'),
  ('Georgia', 'Kutaisi'),
  ('Armenia', NULL),
  ('Armenia', 'Yerevan'),
  ('Armenia', 'Gyumri'),
  ('Azerbaijan', NULL),
  ('Azerbaijan', 'Baku'),
  ('Azerbaijan', 'Ganja'),
  ('Belarus', NULL),
  ('Belarus', 'Minsk'),
  ('Belarus', 'Gomel'),
  ('Belarus', 'Mogilev'),
  ('Moldova', NULL),
  ('Moldova', 'Chisinau'),
  ('Moldova', 'Balti'),
  ('Albania', NULL),
  ('Albania', 'Tirana'),
  ('Albania', 'Durres'),
  ('Albania', 'Vlore'),
  ('North Macedonia', NULL),
  ('North Macedonia', 'Skopje'),
  ('North Macedonia', 'Bitola'),
  ('Montenegro', NULL),
  ('Montenegro', 'Podgorica'),
  ('Montenegro', 'Niksic'),
  ('Bosnia and Herzegovina', NULL),
  ('Bosnia and Herzegovina', 'Sarajevo'),
  ('Bosnia and Herzegovina', 'Banja Luka'),
  ('Kosovo', NULL),
  ('Kosovo', 'Pristina'),
  ('Tunisia', NULL),
  ('Tunisia', 'Tunis'),
  ('Tunisia', 'Sfax'),
  ('Tunisia', 'Sousse'),
  ('Algeria', NULL),
  ('Algeria', 'Algiers'),
  ('Algeria', 'Oran'),
  ('Algeria', 'Constantine'),
  ('Libya', NULL),
  ('Libya', 'Tripoli'),
  ('Libya', 'Benghazi'),
  ('Sudan', NULL),
  ('Sudan', 'Khartoum'),
  ('Sudan', 'Omdurman'),
  ('Ethiopia', NULL),
  ('Ethiopia', 'Addis Ababa'),
  ('Ethiopia', 'Dire Dawa'),
  ('Tanzania', NULL),
  ('Tanzania', 'Dar es Salaam'),
  ('Tanzania', 'Dodoma'),
  ('Tanzania', 'Zanzibar'),
  ('Uganda', NULL),
  ('Uganda', 'Kampala'),
  ('Uganda', 'Entebbe'),
  ('Ghana', NULL),
  ('Ghana', 'Accra'),
  ('Ghana', 'Kumasi'),
  ('Senegal', NULL),
  ('Senegal', 'Dakar'),
  ('Senegal', 'Saint-Louis'),
  ('Ivory Coast', NULL),
  ('Ivory Coast', 'Abidjan'),
  ('Ivory Coast', 'Yamoussoukro'),
  ('Cameroon', NULL),
  ('Cameroon', 'Yaounde'),
  ('Cameroon', 'Douala'),
  ('Zimbabwe', NULL),
  ('Zimbabwe', 'Harare'),
  ('Zimbabwe', 'Bulawayo'),
  ('Zambia', NULL),
  ('Zambia', 'Lusaka'),
  ('Zambia', 'Kitwe'),
  ('Botswana', NULL),
  ('Botswana', 'Gaborone'),
  ('Botswana', 'Francistown'),
  ('Namibia', NULL),
  ('Namibia', 'Windhoek'),
  ('Mauritius', NULL),
  ('Mauritius', 'Port Louis'),
  ('Maldives', NULL),
  ('Maldives', 'Male'),
  ('Brunei', NULL),
  ('Brunei', 'Bandar Seri Begawan'),
  ('Fiji', NULL),
  ('Fiji', 'Suva'),
  ('Papua New Guinea', NULL),
  ('Papua New Guinea', 'Port Moresby'),
  ('Bahrain', NULL),
  ('Bahrain', 'Manama'),
  ('Kuwait', NULL),
  ('Kuwait', 'Kuwait City'),
  ('Qatar', NULL),
  ('Qatar', 'Doha'),
  ('Oman', NULL),
  ('Oman', 'Muscat'),
  ('Jordan', NULL),
  ('Jordan', 'Amman'),
  ('Lebanon', NULL),
  ('Lebanon', 'Beirut'),
  ('Syria', NULL),
  ('Syria', 'Damascus'),
  ('Syria', 'Aleppo'),
  ('Yemen', NULL),
  ('Yemen', 'Sanaa'),
  ('Palestine', NULL),
  ('Palestine', 'Gaza'),
  ('Palestine', 'Ramallah'),
  ('Afghanistan', NULL),
  ('Afghanistan', 'Kabul'),
  ('Tajikistan', NULL),
  ('Tajikistan', 'Dushanbe'),
  ('Kyrgyzstan', NULL),
  ('Kyrgyzstan', 'Bishkek'),
  ('Turkmenistan', NULL),
  ('Turkmenistan', 'Ashgabat'),
  ('Venezuela', NULL),
  ('Venezuela', 'Caracas'),
  ('Venezuela', 'Maracaibo'),
  ('Venezuela', 'Valencia'),
  ('Ecuador', NULL),
  ('Ecuador', 'Quito'),
  ('Ecuador', 'Guayaquil'),
  ('Bolivia', NULL),
  ('Bolivia', 'La Paz'),
  ('Bolivia', 'Santa Cruz'),
  ('Paraguay', NULL),
  ('Paraguay', 'Asuncion'),
  ('Uruguay', NULL),
  ('Uruguay', 'Montevideo'),
  ('Panama', NULL),
  ('Panama', 'Panama City'),
  ('Costa Rica', NULL),
  ('Costa Rica', 'San Jose'),
  ('Guatemala', NULL),
  ('Guatemala', 'Guatemala City'),
  ('Honduras', NULL),
  ('Honduras', 'Tegucigalpa'),
  ('El Salvador', NULL),
  ('El Salvador', 'San Salvador'),
  ('Nicaragua', NULL),
  ('Nicaragua', 'Managua'),
  ('Cuba', NULL),
  ('Cuba', 'Havana'),
  ('Dominican Republic', NULL),
  ('Dominican Republic', 'Santo Domingo'),
  ('Jamaica', NULL),
  ('Jamaica', 'Kingston'),
  ('Haiti', NULL),
  ('Haiti', 'Port-au-Prince'),
  ('Puerto Rico', NULL),
  ('Puerto Rico', 'San Juan'),
  ('Trinidad and Tobago', NULL),
  ('Trinidad and Tobago', 'Port of Spain'),
  ('Bahamas', NULL),
  ('Bahamas', 'Nassau'),
  ('Barbados', NULL),
  ('Barbados', 'Bridgetown'),
  ('Guyana', NULL),
  ('Guyana', 'Georgetown'),
  ('Suriname', NULL),
  ('Suriname', 'Paramaribo'),
  ('Belize', NULL),
  ('Belmopan', NULL),
  ('Antigua and Barbuda', NULL),
  ('Grenada', NULL),
  ('Saint Lucia', NULL),
  ('Saint Vincent and the Grenadines', NULL),
  ('Dominica', NULL),
  ('Saint Kitts and Nevis', NULL),
  ('Seychelles', NULL),
  ('Seychelles', 'Victoria'),
  ('Cape Verde', NULL),
  ('Cape Verde', 'Praia'),
  ('Sao Tome and Principe', NULL),
  ('Equatorial Guinea', NULL),
  ('Gabon', NULL),
  ('Gabon', 'Libreville'),
  ('Congo', NULL),
  ('Congo', 'Brazzaville'),
  ('DR Congo', NULL),
  ('DR Congo', 'Kinshasa'),
  ('Angola', NULL),
  ('Angola', 'Luanda'),
  ('Mozambique', NULL),
  ('Mozambique', 'Maputo'),
  ('Madagascar', NULL),
  ('Madagascar', 'Antananarivo'),
  ('Malawi', NULL),
  ('Malawi', 'Lilongwe'),
  ('Rwanda', NULL),
  ('Rwanda', 'Kigali'),
  ('Burundi', NULL),
  ('Burundi', 'Bujumbura'),
  ('Somalia', NULL),
  ('Somalia', 'Mogadishu'),
  ('Djibouti', NULL),
  ('Djibouti', 'Djibouti City'),
  ('Eritrea', NULL),
  ('Eritrea', 'Asmara'),
  ('South Sudan', NULL),
  ('South Sudan', 'Juba'),
  ('Central African Republic', NULL),
  ('Central African Republic', 'Bangui'),
  ('Chad', NULL),
  ('Chad', 'N Djamena'),
  ('Niger', NULL),
  ('Niger', 'Niamey'),
  ('Mali', NULL),
  ('Mali', 'Bamako'),
  ('Mauritania', NULL),
  ('Mauritania', 'Nouakchott'),
  ('Burkina Faso', NULL),
  ('Burkina Faso', 'Ouagadougou'),
  ('Benin', NULL),
  ('Benin', 'Porto-Novo'),
  ('Togo', NULL),
  ('Togo', 'Lome'),
  ('Liberia', NULL),
  ('Liberia', 'Monrovia'),
  ('Sierra Leone', NULL),
  ('Sierra Leone', 'Freetown'),
  ('Guinea', NULL),
  ('Guinea', 'Conakry'),
  ('Guinea-Bissau', NULL),
  ('Gambia', NULL),
  ('Lesotho', NULL),
  ('Eswatini', NULL),
  ('Comoros', NULL),
  ('Kiribati', NULL),
  ('Marshall Islands', NULL),
  ('Micronesia', NULL),
  ('Nauru', NULL),
  ('Palau', NULL),
  ('Samoa', NULL),
  ('Solomon Islands', NULL),
  ('Tonga', NULL),
  ('Tuvalu', NULL),
  ('Vanuatu', NULL),
  ('East Timor', NULL),
  ('San Marino', NULL),
  ('Vatican City', NULL),
  ('Andorra', NULL);
